spring:
  application:
    name: 331-backend
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3307/selabdb?createDatabaseIfNotExists=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 10MB
supabase:
  storage:
    endpoint:  https://igdfvmiagfmfrjqmuiln.storage.supabase.co/storage/v1/s3
    endpoint_output:   https://igdfvmiagfmfrjqmuiln.storage.supabase.co/storage/v1/object/public
    bucket: lab331
    region: ap-south-1
    accessKey: 0aec57ef5c9c9d58068266918cf24eae
    secretKey: 3206aa5948b8d1bcd54711c861fdf12f59db40a0ed63b9c219af10c32a15d198